# Generated by Django 4.0.6 on 2022-08-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employees_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='empadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
            ],
        ),
    ]
