# Generated by Django 4.0.6 on 2022-08-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_empadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Likes', models.CharField(max_length=10)),
                ('Dislikes', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mothername', models.CharField(max_length=10)),
                ('fathername', models.CharField(max_length=10)),
            ],
        ),
    ]
